# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedFirework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('rarity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireworkInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('firework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firework_users', to='message_app.Firework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fireworks', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='deployedfirework',
            name='firework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='message_app.Firework'),
        ),
        migrations.AddField(
            model_name='deployedfirework',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_fireworks', to='message_app.Message'),
        ),
        migrations.AddField(
            model_name='deployedfirework',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployed_fireworks', to='login_app.User'),
        ),
    ]
