# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_auto_20190626_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployedfirework',
            old_name='user',
            new_name='sent_by',
        ),
    ]
